spring.application.name=AutoRefacciones

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=empresa;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Logi1234!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=60000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


